spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

server:
  port: 8080
  tomcat:
    max-threads: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.seneca.taskmanagement: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
